server:
  port: 8080
  url: http://localhost:${server.port}

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      messaging-app-client:
        client-id: messaging-app-client
        client-secret: secret
        user-authorization-uri: ${server.url}/oauth/authorize
        access-token-uri: ${server.url}/oauth/token
        scope: message.read, message.write
        pre-established-redirect-uri: ${server.url}/messaging

messages:
  base-uri: ${server.url}/messages
