server:
  port: 8092

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

security:
  oauth2:
    resource:
      filter-order: 3
      token-info-uri: http://localhost:8090/oauth/check_token
    client:
      client-id: basic-client
      client-secret: secret