server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      messaging-app-client:
        client-id: messaging-app-client
        client-secret: secret
        user-authorization-uri: http://auth-server:8090/oauth/authorize
        access-token-uri: http://auth-server:8090/oauth/token
        authorized-grant-ypes: authorization_code, refresh_token, password
        scope: message.read, message.write
        pre-established-redirect-uri: http://localhost:8080/messaging/index

messages:
  base-uri: http://localhost:8092/messages
